### ISSUE TITLE
App not working as it should, and I find some bugs!

### ISSUE THREAD

**Issue by coldSeattle** [Archakov06/react-todo#4]
![image](https://user-images.githubusercontent.com/56102448/78437144-81461780-767f-11ea-8aa2-eccea7db0bab.png)

![image](https://user-images.githubusercontent.com/56102448/78437353-8efb9d00-767f-11ea-94b6-3a40d5defa61.png)

при клике на добавить задачу выдает эту ошибку, потом я залез в код и добавил 
![image](https://user-images.githubusercontent.com/56102448/78441640-c7e84180-7680-11ea-84e8-cea7d2d14a48.png)

типо это ок
но потом  и пошли ошибки с колорс типа 0 of null и т.д.
так как я пока в процессе обучения не могу решить все эти друг за дуржком проблемы, поэтому вместо форка с пул реквестом сделал issue.

**Comment by coldSeattle** [comment]
> ![image](https://user-images.githubusercontent.com/56102448/78437144-81461780-767f-11ea-8aa2-eccea7db0bab.png)
> 
> ![image](https://user-images.githubusercontent.com/56102448/78437353-8efb9d00-767f-11ea-94b6-3a40d5defa61.png)
> 
> при клике на добавить задачу выдает эту ошибку, потом я залез в код и добавил
> ![image](https://user-images.githubusercontent.com/56102448/78441640-c7e84180-7680-11ea-84e8-cea7d2d14a48.png)
> 
> типо это ок
> но потом и пошли ошибки с колорс типа 0 of null и т.д.
> так как я пока в процессе обучения не могу решить все эти друг за дуржком проблемы, поэтому вместо форка с пул реквестом сделал issue.

bug :bug:

**Comment by Archakov06** [comment]
Пришли PR, я чекну и залью, если ок

**Comment by coldSeattle** [comment]
там проблема у меня было и я ее решил. но также нашел баг в другом месте, пофиксил и сделал PR.
