### ISSUE TITLE
colors is not exists?

### ISSUE THREAD

**Issue by Mechetel** [Archakov06/react-todo#7]
https://github.com/Archakov06/react-todo/blob/498691b74249d3842d935f8f8599468ddaf922a1/src/components/AddList/index.jsx#L107
<img width="1064" alt="Screenshot 2020-07-28 at 22 05 43" src="https://user-images.githubusercontent.com/26309618/88709907-7e839c80-d11e-11ea-90d7-b3c1fb90d859.png">

**Comment by juridicalHead** [comment]
I have faced with the same problem. Has anybody solved it?
